hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

spring:
  application:
    name: tridato-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://trudata-eureka.us-east-2.elasticbeanstalk.com/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false

zuul:
  routes:
    users:
      path: /police/**
      serviceId: tridato-co-police
    mintransporte:
      path: /mintransporte/**
      serviceId: tridato-co-mintransporte
    aguascalientes:
      path: /aguascalientes/**
      serviceId: tridato-mx-aguascalientes
    sipso:
      path: /sipso/**
      serviceId: tridato-mx-sipso

tridato-co-police:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
tridato-co-mintransporte:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
tridato-mx-aguascalientes:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

tridato-mx-sipso:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000


