hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

spring:
  application:
    name: tridato-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
  instance:
    hostname: localhost

server:
    port: 8765

zuul:
  routes:
    users:
      path: /police/**
      serviceId: tridato-co-police
    mintransporte:
      path: /mintransporte/**
      serviceId: tridato-co-mintransporte
    aguascalientes:
      path: /aguascalientes/**
      serviceId: tridato-mx-aguascalientes

tridato-co-police:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
tridato-co-mintransporte:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000
tridato-co-aguascalientes:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000