spring:
  application:
    name: tridato-co-mintransporte

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}