version: "3"
services:
    database:
        build:
            context: .
            dockerfile: db_dockerfile
        ports: ['127.0.0.1:3306:3306']
        networks:
            - trudatanetwork
        container_name: trudata_aguascalientes_db
    scraper:
        build:
            context: .
            dockerfile: scraper_dockerfile
        networks:
            - trudatanetwork
        container_name: trudata_aguascalientes_scraper
        depends_on: ['database']

networks: {trudatanetwork:{}}
