spring:
  application:
    name: tridato-mx-sipso

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}

trudato:
  mx:
    sipso:
      url:
        index: http://sipso.sedesol.gob.mx/consultarCurp/consultaCurpR.jsp?cveCurp=%s
      selector:
        curp: "#consultaCurp > table > tbody > tr:nth-child(2) > td:nth-child(2)"
        lastName: "#consultaCurp > table > tbody > tr:nth-child(3) > td:nth-child(2)"
        secondLastName: "#consultaCurp > table > tbody > tr:nth-child(4) > td:nth-child(2)"
        name: "#consultaCurp > table > tbody > tr:nth-child(5) > td:nth-child(2)"
        gender: "#consultaCurp > table > tbody > tr:nth-child(6) > td:nth-child(2)"
        birthday: "#consultaCurp > table > tbody > tr:nth-child(7) > td:nth-child(2)"
        birthdayEntity: "#consultaCurp > table > tbody > tr:nth-child(8) > td:nth-child(2)"